name: "HA Unique ID Patch"
version: "1.0.12"
slug: "ha_unique_id_patch"
description: "GUIから config_entries の unique_id を直接編集・修正するためのアドオンです。"
url: "https://github.com/666mk3/ha-unique-id-patch"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
boot: manual
hassio_role: manager
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:identifier
panel_title: "ID Patch"
map:
  - config:rw
options:
  log_level: info
schema:
  log_level: str
